### ISSUE TITLE
fileDerivationVars example

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#11]
Looking at the fileDerivationVars element in the codebook.xsd schema, in the 2023 draft of the Codebook 2.6 there was previously an example:
```
<keep>V1 V2 V5</keep>
<drop>V3</drop>
<add>V16</add>
```

It was subsequently modified (in the current GitHub version) to:
```
<fileCommand>
    <fileDerivationsVars keep="V1 V2 V5" drop="V3" add="V16"/>
</fileCommand>
```

This suggests that keep, drop and add are treated as attributes, however the fileDerivationVarsType mentions them as children:
```
<xs:attribute name="keep" type="xs:IDREFS" use="optional"/>
<xs:attribute name="drop" type="xs:IDREFS" use="optional"/>
<xs:attribute name="add" type="xs:IDREFS" use="optional"/>
```

So is the (new) example correct or is it out of sync with the schema?

Best,
Adrian

**Comment by wlthomas** [comment]
I will check on this. There was a lot of shifting on the structure of this
and so the documentation  may have gotten unalignedwith the final version.

**Comment by DanSmith** [comment]
They are defined as `xs:attribute`'s, what is meant by the term children?

**Comment by wlthomas** [comment]
I searched the term children in the codebook.xsd and found it only in appropriate locations such as documentation on groups, and as topic terms in vars and ncubes. As Dan stated these are now attributes so that they are consistent with other uses of IDRefs within the schema.

**Comment by dusadrian** [comment]
Oh, I see... my bad.
They were previously defined as xs:element, and now changed to xs:attribute.
Sorry for the noise,
Adrian
