### ISSUE TITLE
examples in the "label" element unclear

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#12]
I noticed the element "label" is the only element in the schema that has two `<xs:documentation>`s in the `<xs:annotation>` field.

The descriptions are different, and the second one has some examples. But it is not clear from the examples how it applies, since all examples use the element `<labl>` instead of `<label>`.

This is carried over from as far as version 2.1, if I am not mistaken. Perhaps this could be clarified, especially the difference from the element `<labl>`.

**Comment by wlthomas** [comment]
"label" is part of the formType
This type defines the basis for all elements in the FORM content group. This is derived from the abstractTextType. The content may still be mixed (text and child elements), but the child elements are restricted to be those from the PHRASE and FORM content groups, or the itm and label elements.

These were pulled in from another standard and we copied the terms verbatim. The native DDI element is labl, however we do seem to use an attribute "label" in relMatType and setAvailType. Reasoning is lost to the mysteries of time as these are very early elements to show up in DDI Codebook.

**Comment by wlthomas** [comment]
Ah now i see the problem (needed more caffine) the labl examples and documentation were added to label. I'll fix that

**Comment by wlthomas** [comment]
Resolution:
REMOVE documentation section at 724 from "label"
EDIT documentation at 5010 to add some of the examples removed from "label"

**Comment by dusadrian** [comment]
> ...
> These were pulled in from another standard and we copied the terms verbatim. The native DDI element is labl, however we do seem to use an attribute "label" in relMatType and setAvailType. Reasoning is lost to the mysteries of time as these are very early elements to show up in DDI Codebook.

There is indeed an attribute "label", but here I am referring to the element "label".
It doesn't seem to be used much, but it is not flagged as deprecated either. Perhaps it should be deprecated...?

**Comment by wlthomas** [comment]
No it should not be deprecated. It is part of the PHRASE FORM plus itm and
label.

I'll see if I can find an example and will make sure this is part of the
high level document.

**Comment by wlthomas** [comment]
resolved with pull request #12
