### ISSUE TITLE
standardized documentation

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#18]
Referring to earlier issues, I do understand the Schema and the html files are manually crafted (huge thanks for your work, people).

Now, taking for example this issue regarding [typeOfAccess](https://github.com/ddialliance/ddi-c_2/issues/17), there are sometimes typos in the documentation, which is normal under these circumstances.

But I do feel the need to somehow standardize the description field. The use case scenario, for me, is to separate the description of the element itself from the description of its attributes. When parsing the Schema, I would like to completely extract an attribute description from the element's description.

For instance, in the description of the element "abstract" I see:
```
The "date" attribute should follow ISO convention of YYYY-MM-DD. The contentType
attribute provides forward-compatibility with DDI Lifecycle by describing where the
content fits in that structure, or if is mixed  [abstract | purpose | mixed] in terms
of what is contained.
```
Here, the attribute "date" is quoted while contentType is not.

In the element "qstn", the decription looks like this:
```
The question element may have mixed content. The element itself may contain text for
the question, with the subelements being used to provide further information about the
question. Alternatively, the question element may be empty and only the subelements
used. The element has a unique question ID attribute which can be used to link a variable
with other variables where the same question has been asked. This would allow searching
for all variables that share the same question ID, perhaps because the questions was
asked several times in a panel design. The "ID" attribute contains a unique identifier
for the question. "Var" references the ID(s) of the variable(s) relating to the question.
The attribute "seqNo" refers to the sequence number of the question. The attribute
"sdatrefs" may be used to reference elements in the summary data description section
of the Study Description which might apply to this question. The attribute "access"
records the ID values of all elements in the Data Access and Metadata Access section
that describe access conditions for this question. These elements include: time period
covered, date of collection, nation or country, geographic coverage, geographic unit,
unit of analysis, universe, and kind of data. The responseDomainType attribute was added
to capture the specific DDI Lifecycle response domain type to facilitate translation
between DDI 2 and DDI Lifecycle. If this is given a value of "other" then a term from a
controlled vocabulary should be put into the "otherResponseDomainType" attribute.
```

Sometimes, the attributes are described as
`The "ID" attribute` while other times as
`The attribute "seqNo"`, and in some cases simply as
`"Var" references...` (as reported before, "Var" is probably meant as "var")

I am not aware if the Schema allows to describe attributes separately from the elements (probably not), therefore the bundled description of all. If separating these descriptions (after parsing the Schema), the element's description would become lighter and easier to follow, while interested users would look at the description of the arguments if further interested.

But to do this, the element's description would need to be standardized. If useful, I volunteer to review all elements and re-arrange their description, provided an agreed (standard) description template.

**Comment by wlthomas** [comment]
I will bring this to the TC but I think it may be an issue for post 2.6
Codebook Working Group to address.

**Comment by dusadrian** [comment]
Thanks, the description would remain the same. What changes is the structure, much like the one from the element "embargo":
```
<xhtml:div class="description">
   <xhtml:p>Provides information on variables/nCubes which are not currently available because of policies established by the principal investigators and/or data producers. The ISO standard for dates (YYYY-MM-DD) is recommended for use with the "date" attribute. An "event" attribute is provided to specify "notBefore" or "notAfter" ("notBefore" is the default). A "format" attribute is provided to ensure that this information will be machine-processable, and specifies a format for the embargo element.</xhtml:p>
   <xhtml:p>The "format" attribute could be used to specify other conventions for the way that information within the embargo element is set out, if conventions for encoding embargo information were established in the future.</xhtml:p>
   <xhtml:p>This element may be repeated to support multiple language expressions of the content.</xhtml:p>
</xhtml:div>
```

I think it would bring a lot of value if re-arranging the descriptions using `<xhtml:p>` paragraphs. No extra work would be needed, since I volunteer to do it myself.

Otherwise, I learned that simpleTypes do accept annotations / documentations, so the description of the attribute can actually be done right within the attribute.

I know the TC is eager to release version 2.6, it is just amazing to me that this wasn't done yet, and there are decades since the Codebook is around...

**Comment by wlthomas** [comment]
I will take up your offer to do this work with TC at our next meeting. In
terms of timing such a change may best be made right before packaging. It
was decided this week to delay the switch to a consistent use of spacing
for indent should wait until then. This making it easier to track changes
made in content. Also we will be determining a format validation which
GitHub will use in future merge processing. My one other concern is the
software we use to create the html field level documentation. Jon knows the
constraints of this.

**Comment by DanSmith** [comment]
At this week's TC meeting, we discussed the current attribute documentation and if it makes sense to add explicit documentation at the attribute level such as
```xml
<xs:attribute name="..." ...>
  <xs:annotation>
    <xs:documentation>...</xs:documentation>
  </xs:annotation>
</xs:attribute>
```
