### ISSUE TITLE
catStat attributes

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#20]
In the description of the element `catStat`, we have:
```
<xhtml:p>The following attributes provide information on the weighting used ... </xhtml:p>
<xhtml:p>"wgtd" expressed as wgtd or not-wgtd, </xhtml:p>
<xhtml:p>"wgt-var" a reference to the variable containing the weight used or </xhtml:p>
<xhtml:p>"wgt" the value of a standard weight.</xhtml:p>
```
From this description, I get that either "wgt-var" `or` "wgt" attributes can be used.
If so, shouldn't these attributes be enclosed into an `<xs:choice>` validation?

**Comment by wlthomas** [comment]
Attributes are all 0..1 unless declared as required or provided with a
default value in which case they are 1..1

Choice is only valid for elements. Note also that attributes are not found
within sequence as they have no specified order.

**Comment by dusadrian** [comment]
I see.
For some reason, I thought all complexContents can be wrapped in a `xs:choice` but that is indeed possible for elements only.
