### ISSUE TITLE
catgryGrp attributes

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#21]
Two of this element's attributes, `compl` and `excls` are defined as xs:NMTOKEN, with only two values: true and false.
Many other attributes are defined as xs:boolean, shouldn't these attributes be the same?

The attribute `catgry` is listed but no description of it can be found in the element's documentation, and there are no examples to at least infer its purpose.

**Comment by wlthomas** [comment]
These 2 attributes have existed in this format since the beginning.
Retaining this limit disallows the use of 0 | 1. Maybe something for a
future discussion of structural change to Codebook but not for 2.6

I'll add documentation on catgry attribute.

**Comment by wlthomas** [comment]
Source verification: these attributes were added in the 2.0 version of the DTD and transformed into the schema using a restriction base of NMTOKEN for all internal enumerations. Later additions to the schema brought in the use of xs:boolean. 

Added documentation on the use of the attributes "catgry" and "catGrp".
Use the attribute "catgry" (IDREFS type) to provide a space delimited list of the ID of each category in the parent category group. The attribute "catGrp" (IDREFS type) is used to indicate all the subsidiary category groups which nest underneath the current category group. This allows for the encoding of a hierarchical structure of category groups. Do not list the categories contained in a listed "catGrp" within the attribute "catgry". These two IDREFS attributes should list ONLY the direct children of the parent category group.

THIS WILL BE IN NEXT PULL REQUEST FOR JULY 23
