### ISSUE TITLE
no documentation for colspec

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#22]
The element `colspec` to describe column specification, has no documentation at all.
And it has a good number of attributes. For some, the use case can be deduced, like `colname` or `colwidth`.
Not very clear what the attribute `charoff` does, without more detailed documentation. Even `rowsep` (presumably referring to row separation, resembling an EOL) is difficult to understand in documenting a column.

**Comment by wlthomas** [comment]
Will add documentation
