### ISSUE TITLE
Inexistent attribute vocabVersionID

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#23]
A number of elements (concept, format, keyword, nation and topcClas) mention in their description:
```
... "vocabAgencyName" and "vocabAgencyID" to specify the agency managing the controlled
vocabulary ...
```
but no element in the whole schema has this attribute `vocabAgencyID `.
If it was intended as a new attribute, it wasn't added in the schema. Otherwise, the documentation refers to inexistent attributes.

**Comment by wlthomas** [comment]
Will check further on this. There were some shifts back and forth on this
and I'll trace back the final decision and implement accordingly.

**Comment by wlthomas** [comment]
"vocabAgencyName" is in conceptType. Will verify other locations.

**Comment by wlthomas** [comment]
Agreed contents were: I will verify and make sure documentation and examples match
Content for Codebook 2.5 Concept and related items
vocabID
vocab
vocabAgency
vocabVersionID
otherValue
vocabURI
[deprecate]
vocabInstanceURI
vocabInstanceCodeTerm
xml:lang
[content: label]*

**Comment by dusadrian** [comment]
That is what I saw, too.
So the documented attribute `vocabAgencyID` (despite being mentioned) was left out and should probably be removed from the description.

**Comment by wlthomas** [comment]
The intent was to add the attribute to align with lifecycle. I'll double
check and add.

**Comment by wlthomas** [comment]
11 instances
CHANGED documenation FROM "an "vocabAgencyName" and "vocabAgencyID" to specify the agency managing" TO "a "vocabAgencyName" to specify the agency managing" in all documentation


IN PULL REQUEST FOR JULY 25
