### ISSUE TITLE
redundant documentation

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#25]
Elements: depositr, distrbtr, fundAg, origArch etc (there are 11 of them) have two redundant descriptions:

```
An agent may be an organization or individual.
```
and
```
Use "agentType" to indicate if the agent is an organization or an individual.
```
The first was there in version 2.5, but introducing "agentType" in version 2.6 makes that description redundant.

**Comment by wlthomas** [comment]
Will correct

**Comment by wlthomas** [comment]
REMOVED as redundant "An agent may be an organization or individual." holdover from when there was no indictor for individual or organization status.
