### ISSUE TITLE
typo in the example of element contact

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#30]
```
<contact affiliation="University of Wisconsin" email="jsmith@wisc.edu" URI="wisc.edu"
agentIdentifier="0000-0003-1294-0000" typeOfAgentIdentifier="orchid">Jane Smith</contact>
```

In the `typeOfAgentIdentifier="orchid"`, the type is supposed to be "orcid", and perhaps in caps, "ORCID".
The element othId also has lower letters "orcid".

**Comment by wlthomas** [comment]
Checked entire xsd. Found and corrected one instance of misspelling  of "orcid" in "contact" example
