### ISSUE TITLE
description of fileType

### ISSUE THREAD

**Issue by dusadrian** [ddialliance/ddi-c_2#33]
This contains the following:
"Note that the element varFormat permits specification of the data format at the variable level."

It is not immediately clear what the element varFormat has to do with the element fileType. It is neither a parent, nor a child of this element.

**Comment by wlthomas** [comment]
The purpose is to differentiate between the overall file type format and
the format of a variable. It was probably added at some point in response
to a direct user query. This should be expanded to something like: this
element refers to the format of the overall data file. If you need to
specify the format of individual variables within the data file use
"varFormat" found in the element "var".

Is that clearer?

**Comment by dusadrian** [comment]
Yes, this is much more clear now. Thanks a lot.
